--LIKE

/* ENCONTRE NO BANCO DE DADOS TODAS AS PESSOAS QUE POSSUAM 'OVI' NO INICIO DO NOME */ 

SELECT *
FROM Person.Person
WHERE FirstName LIKE 'OVI%'
ORDER BY BusinessEntityID


/* ENCONTRE NO BANCO DE DADOS TODAS AS PESSOAS QUE POSSUAM 'TO' NO FINAL DO NOME */

SELECT *
FROM Person.Person
WHERE FirstName LIKE '%TO'
ORDER BY BusinessEntityID


/* ENCONTRE NO BANCO DE DADOS TODAS AS PESSOAS QUE POSSUAM 'ESSA' NO MEIO DO NOME */

SELECT *
FROM Person.Person
WHERE FirstName LIKE '%ESSA%'
ORDER BY BusinessEntityID


/*O CARACTER '_' PODE SUBSTITUIR UM CARACTER QUE VOCÊ NÃO CONHEÇA NA PALAVRA QUE ESTÁ BUSCANDO */
SELECT *
FROM Person.Person
WHERE FirstName LIKE '%RO_'
ORDER BY BusinessEntityID