SELECT top 5 *
FROM Production.Product


/* QUANTOS TITULOS UNICOS ESTÃO PRESENTES*/

SELECT COUNT(DISTINCT TITLE)
FROM Person.Person


/*QUANTOS PRODUTOS TEMOS CADASTRADOS NA TABELA DE PRODUTOS*/

SELECT COUNT(Name) AS "PRODUTOS_CADASTRADOS"
FROM Production.Product


/*QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADOS NA TABELA DE PRODUTOS*/

SELECT COUNT(Size) AS "TAMANHOS"
FROM Production.Product


/*QUANTOS TAMANHOS DIFERENTES DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS*/

SELECT COUNT(DISTINCT Size) AS "TAMANHOS_UNICOS"
FROM Production.Product

