--ORDER BY

SELECT FirstName, LastName
FROM Person.Person
ORDER BY FirstName ASC, LastName DESC


/*OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO PARA O MAIS BARATO*/

SELECT TOP 10 ProductID
FROM Production.Product
ORDER BY ListPrice DESC


/*OBTER O NOME E O NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O PRODUCTID ENTRE 1~4*/

SELECT TOP 4 Name, ProductNumber
FROM Production.Product
WHERE ProductID >= 1 AND ProductID <= 4

