/* RETORNE OS 10 PRIMEIROS ELEMENTOS DA TABELA PRODUCTION*/

SELECT TOP 10 *
FROM Production.Product


/*RETORNE OS 50 PRIMEIROS ELEMENTOS DA TABELA PERSON*/

SELECT TOP 50 *
FROM Person.Person