/*A EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE OS NOMES MAIS COMUNS DE SEUS CLIENTES */
/*E PRECISA DO NOME E SOBRENOME DE TODOSOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.*/

SELECT firstName, lastName
FROM Person.Person;

