--GROUP BY

SELECT SpecialOfferID, SUM(UNITPRICE) AS 'SOMA'
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID


/* QUANTO DE CADA PRODUTO FOI VENDIDO NO TOTAL SEPARANDO POR ITEM */

SELECT ProductID AS 'PRODUTO', SUM(OrderQty) AS 'QUANTIDADE'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY QUANTIDADE


/* QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS NO NOSSO BANCO DE DADOS */

SELECT FirstName AS 'NOME', COUNT(FirstName) AS 'QUANTIDADE'
FROM Person.Person
GROUP BY FirstName
ORDER BY QUANTIDADE DESC


/* QUAL É A MEDIA DE PREÇO DOS PRODUTOS QUE SÃO PRATAS */

SELECT Color AS 'COR', AVG(ListPrice) AS 'MEDIA_PRECO'
FROM Production.Product
WHERE Color = 'Silver'
GROUP BY Color


/* PRECISO SABER QUANTAS PESSOAS TEM O MESMO NOME DO MEIO */

SELECT MiddleName AS 'NOME_DO_MEIO', COUNT(MiddleName) AS 'QUANTIDADE'
FROM Person.Person
GROUP BY MiddleName
ORDER BY QUANTIDADE DESC


/* EM MEDIA QUAL É A QUANTIDADE QUE CADA PRODUTO É VENDIDO NA LOJA */

SELECT ProductID AS 'PRODUTO', AVG(OrderQty) AS 'MEDIA'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY MEDIA DESC


/* QUAL FOI O TOP 10 DE VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA POR PRODUTO DO MAIOR VALOR PARA O MENOR */

SELECT TOP 10 ProductID, SUM(LineTotal) AS 'MAIORES_VALORES'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY MAIORES_VALORES DESC


/* QUANTOS PRODUTOS E QUAL É A QUANTIDADE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS NOSSAS ORDEM DE SERVIÇO, AGRUPADOS POR ID DO PRODUTO */

SELECT ProductID AS 'ID_PRODUTO', COUNT(ProductID) as 'QUANTIDADE', AVG(WORKORDERID) AS 'MEDIA'
FROM Production.WorkOrder
GROUP BY ProductID
ORDER BY ID_PRODUTO






