--AS 

SELECT TOP 10 ListPrice AS 'PRECO_DO_PRODUTO'
FROM Production.Product


SELECT TOP 10 AVG(ListPrice) AS 'PRECO_MEDIO'
FROM Production.Product


/* ENCONTRAR O FIRSTNAME E LASTNAME DA TABELA PERSON.PERSON E RETORNE COM O NOME EM PORTUGUES */

SELECT FirstName AS 'NOME', LastName AS 'SOBRENOME'
FROM Person.Person
ORDER BY NOME, SOBRENOME


/* PRODUCTNUMBER DA TABELA PRODUCTION.PRODUCT RENOMEIE PARA 'NUMERO DO PRODUTO' */

SELECT ProductNumber AS 'NUMERO_DO_PRODUTO'
FROM Production.Product
ORDER BY NUMERO_DO_PRODUTO


/* SALES.SALESORDERDETAIL RENOMEIE UNITPRICE PARA 'PRECO UNITARIO' */

SELECT UnitPrice AS 'PRECO_UNITARIO'
FROM Sales.SalesOrderDetail
ORDER BY PRECO_UNITARIO