--HAVING

/* RETORNE TODOS OS PRIMEIROS NOMES COM A INCIDENCIA MAIOR QUE 10, ORGANIZADO POR ORDEM ALFABETICA */

SELECT FirstName AS 'PRIMEIRO_NOME', COUNT(FirstName) AS 'QUANTIDADE'
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 10
ORDER BY PRIMEIRO_NOME ASC


/* QUAIS PRODUTOS QUE NO TOTAL DE VENDAS ESTÃO ENTRE 162K A 500K */

SELECT ProductID AS 'PRODUTO', SUM(LineTotal) as 'TOTAL_VENDIDO'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000
ORDER BY TOTAL_VENDIDO DESC


/* QUAIS NOMES NO SISTEMA TEM UMA OCORRENCIA MAIOR QUE 10 VEZES, POREM SOMENTE ONDE O TITULO É 'MR.' */

SELECT FirstName AS 'NOME', COUNT(FirstName) AS 'QUANTIDADE'
FROM Person.Person
WHERE TITLE = 'MR.'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10
ORDER BY QUANTIDADE ASC


/* ESTAMOS QUERENDO IDENTIFICAR AS PROVINCIAS COM MAIOR NUMERO DE CADASTROS NO NOSSO SISTEMA, 
ENTÃO É PRECISO ENCONTRAR QUAIS PROVINCIAS ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS QUE 1000 VEZES */

SELECT StateProvinceID, COUNT(StateProvinceID) as 'QUANTIDADE'
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000
ORDER BY QUANTIDADE ASC


/* EM UMA MULTINACIONAL OS GERENTES QUEREM SABER QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MÉDIA NO MÍNIMO 1 MILHÃO EM TOTAL DE VENDAS */

SELECT ProductID AS 'PRODUTO', AVG(LineTotal) as 'MEDIA_VENDIDA'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000000
ORDER BY MEDIA_VENDIDA ASC
